name: Run Python Tests with Pytest

# Triggers the workflow on push and pull request
on:
  push:
  pull_request:

jobs:
  test-python-code:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file found"
          pip install pytest  # Ensure pytest is installed

      - name: Run Unit Tests with Pytest
        run: pytest --junitxml=pytest-report.xml
        # Runs all tests and generates a JUnit-style report

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml
        # Stores the test results as an artifact
